# Generated by Django 5.2.14 on 2026-05-20 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(blank=True, help_text='The original chunk of notes this KU was derived from.')),
                ('concept_summary', models.TextField(help_text='One- to two-sentence summary of the concept this KU teaches.')),
                ('key_terms', models.JSONField(blank=True, default=list, help_text='List of key terms / definitions for this concept.')),
                ('blooms_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', max_length=20)),
                ('connection_tags', models.JSONField(blank=True, default=list, help_text='Concept tags / topics this KU connects to.')),
                ('common_misconceptions', models.JSONField(blank=True, default=list, help_text='Common misconceptions the AI flagged for this concept.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_units', to='courses.section')),
            ],
            options={
                'ordering': ['section_id', 'id'],
            },
        ),
    ]
