# Generated by Django 5.2.14 on 2026-05-20 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('flashcard', 'Flashcard'), ('mc', 'Multiple choice'), ('scenario', 'Scenario'), ('fill_blank', 'Fill in the blank'), ('free_response', 'Free response')], max_length=20)),
                ('prompt', models.TextField()),
                ('expected_answer', models.JSONField(default=dict)),
                ('distractors', models.JSONField(blank=True, default=list)),
                ('blooms_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', max_length=20)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_items', to='learning.knowledgeunit')),
            ],
            options={
                'ordering': ['knowledge_unit_id', 'mode', 'id'],
            },
        ),
    ]
