# Generated by Django 5.2.14 on 2026-05-20 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0002_studyitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('was_correct', models.BooleanField()),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, help_text='0-5 self-rating (Anki-style). Optional in V1.', null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('study_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='learning.studyitem')),
            ],
            options={
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['study_item', '-reviewed_at'], name='reviews_rev_study_i_94661c_idx')],
            },
        ),
    ]
