# Generated by Django 5.2.14 on 2026-05-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Editable raw notes for this section. The Ingest action reads from this field to generate knowledge units.'),
        ),
    ]
